version: '3.8'
services:
  cache:
    image: redis:7.2.3
    expose:
      - 6379
  api:
    build: .
    # image: bunnana/cleverse-backend-project-api:ci.docker-build-5912ecb
    environment:
      - PORT=8080
      - REDIS_URL=redis://cache:6379
    ports:
      - 8080:8080
    depends_on:
      - cache
    secrets:
      - service-account
# volumes:
#   cleverse-backend-db-volume:

secrets:
  service-account:
    file: service-account.json
