version: '3.8'
services:
  cache:
    image: redis:7.2.3
    expose:
      - 6379
  webpage:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}-web:0.0.1
    ports:
      - 80:80
  api:
    # build: .
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}-api:0.1.0-delta
    environment:
      - PORT=8080
      - REDIS_URL=redis://cache:6379
    ports:
      - 8080:8080
    depends_on:
      - cache
    secrets:
      - service-account
  deployer:
    image: cloudiana/compose-deployment:0.0.5
    ports:
      - 3000:3000
    environment:
      - CD_HOST_COMPOSE_WORKING_DIR=/home/admin/puadlhang-dev
    env_file:
      - .env.prod
    volumes:
      - .env.prod:${PRODUCTION_DIR}/.env.prod
      - ./compose.yml:/bin/compose.yml
      - /var/run/docker.sock:/var/run/docker.sock
    secrets:
      - pubkey
# volumes:
#   cleverse-backend-db-volume:

secrets:
  service-account:
    file: service-account.json
  pubkey:
    file: cd_public.pem
